# Generated by Django 5.2.6 on 2025-09-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
