# Generated by Django 5.2.6 on 2025-09-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
