# Generated by Django 5.2.6 on 2025-10-12 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_image'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='photo',
        #     name='comments',
        #     field=models.CharField(default=django.utils.timezone.now, max_length=200),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='photo',
        #     name='likes',
        #     field=models.IntegerField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
    ]
