# Generated by Django 5.2.6 on 2025-10-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_comments_photo_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='upload_time',
        ),
    ]
