# Generated by Django 5.2.6 on 2025-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_remove_photo_upload_time'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='photo',
        #     name='likes',
        #     field=models.IntegerField(default=0),
        # ),
    ]
