# Generated by Django 5.2.6 on 2025-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_remove_photo_likes'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='photo',
        #     name='comments',
        # ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
