# Generated by Django 5.2.6 on 2025-11-10 03:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='UserComments',
        ),
        migrations.RenameField(
            model_name='usercomments',
            old_name='Comment',
            new_name='comment',
        ),
    ]
